### ISSUE TITLE
Edit About text

### ISSUE THREAD

**Issue by stephlocke** [lockedata/sqlserverinternals#3]
[Amend](https://help.github.com/articles/editing-files-in-your-repository/) copy [about the company](https://github.com/lockedata/sqlserverinternals/blob/master/content/home/about.md#advanced-sql-training)

**Comment by kalendelaney** [comment]
**# Advanced SQL Server Training**

Kalen Delaney teaches the most advanced SQL Server courses in the world. Her 5-day course “SQL Server Internals and Tuning” is designed for advanced SQL Server professionals who want to know how SQL Server really works, in order to take maximum advantage of its potential.

Kalen also offers a reduced 3-day course focusing on Query Tuning, as well as one-day seminars on a variety of internals and performance related topics.
